_prefs: 
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 39.2379
  - -6.7994
  - 14
description: A map of rivers, streams, drains, and weltlands based on Mapbox's monotone basemap.
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 21
minzoom: 0
name: Dar Drainage Map
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
  - drainage.mss
template: ''
